// #pragma once
#include "component/ai.hpp"
#include "component/attacker.hpp"
#include "component/destructible.hpp"
#include "component/enemy.hpp"
#include "component/movable.hpp"
#include "component/player.hpp"
#include "component/position.hpp"
#include "component/renderable.hpp"
#include "component/vchar.hpp"
#include "component/viewshed.hpp"